from runtime_data import load_runtime_table
# Auto-generated by rescouces/tools/collect_push_ids.py. Do not edit by hand.
# SYSTEM_IDS: all system ids -> sc_10600 open_system (all systems unlocked)
# STAGE_IDS: main-story (ChapterCfg.type==1) stage ids -> sc_24009 user_chapter_list
# SHOP_GOODS_NOREFRESH: shop_id -> goods_id list, shop_refresh ~= 2 only
#   (the client auto-fills refresh==2 goods; these must ride the sc_20009 init frame)
# ALL_CURRENCY_IDS: every currency item id (CurrencyIdMapCfg) -> sc_15009 currency_list
SYSTEM_IDS = load_runtime_table("SYSTEM_IDS")
STAGE_IDS = load_runtime_table("STAGE_IDS")
SHOP_GOODS_NOREFRESH = load_runtime_table("SHOP_GOODS_NOREFRESH")
ALL_CURRENCY_IDS = load_runtime_table("ALL_CURRENCY_IDS")
